# Generated by Django 5.1.15 on 2026-04-24 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model("users", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_profiles_for_existing_users, noop_reverse),
    ]
