# Generated by Django 5.1.15 on 2026-04-24 00:54

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def backfill_wallet_for_existing_users(apps, schema_editor):
    Category = apps.get_model("budget", "Category")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    for user in User.objects.all():
        if Category.objects.filter(user=user, is_primary=True).exists():
            continue

        existing_wallet = Category.objects.filter(user=user, name="Wallet").first()
        if existing_wallet:
            existing_wallet.is_primary = True
            existing_wallet.save(update_fields=["is_primary"])
            continue

        Category.objects.create(
            user=user,
            name="Wallet",
            slug="wallet",
            description="Unallocated income waiting to be budgeted.",
            color="#0f172a",
            icon="wallet",
            monthly_budget=Decimal("0.00"),
            is_primary=True,
        )


def noop_reverse(apps, schema_editor):
    # Primary-flag rollback is handled by dropping the column itself.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='one_primary_category_per_user'),
        ),
        migrations.RunPython(backfill_wallet_for_existing_users, noop_reverse),
    ]
